export default {
  login: "gastonNet",
  id: 75463604,
  node_id: "MDQ6VXNlcjc1NDYzNjA0",
  avatar_url: "https://avatars.githubusercontent.com/u/75463604?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/gastonNet",
  html_url: "https://github.com/gastonNet",
  followers_url: "https://api.github.com/users/gastonNet/followers",
  following_url:
    "https://api.github.com/users/gastonNet/following{/other_user}",
  gists_url: "https://api.github.com/users/gastonNet/gists{/gist_id}",
  starred_url: "https://api.github.com/users/gastonNet/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/gastonNet/subscriptions",
  organizations_url: "https://api.github.com/users/gastonNet/orgs",
  repos_url: "https://api.github.com/users/gastonNet/repos",
  events_url: "https://api.github.com/users/gastonNet/events{/privacy}",
  received_events_url: "https://api.github.com/users/gastonNet/received_events",
  type: "User",
  site_admin: false,
  name: "Gaston Perez",
  company: null,
  blog: "",
  location: "San Luis, Argentina",
  email: null,
  hireable: null,
  bio: "Front end | Web developer | ReactJS\r\n",
  twitter_username: null,
  public_repos: 9,
  public_gists: 0,
  followers: 0,
  following: 5,
  created_at: "2020-12-04T03:48:01Z",
  updated_at: "2022-03-03T00:08:02Z",
};
